export interface Product {
  id: string;
  name: string;
  brand: string;
  category: string;
  sku: string;
  price_cents: number;
  rating: number;
  reviews_count: number;
  stock: number;
  image_url: string;
  description: string;
  specs: Record<string, string>;
  carrier_default: 'USPS' | 'FEDEX' | 'UPS';
}

export const PRODUCTS: Product[] = [
  // ── 1. Drones & Cameras (8 products) ──
  {
    id: "prod_1",
    name: "DJI Mavic 3 Pro Cine Drone",
    brand: "DJI",
    category: "Drones & Cameras",
    sku: "DJI-M3P-CINE",
    price_cents: 219900,
    rating: 4.9,
    reviews_count: 328,
    stock: 14,
    image_url: "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?auto=format&fit=crop&w=600&q=80",
    description: "Flagship triple-camera system featuring Hasselblad 4/3 CMOS, dual tele-cameras, 43-min flight time, and omnidirectional obstacle sensing.",
    specs: { "Sensor": "4/3 CMOS Hasselblad", "Video": "5.1K/50fps Apple ProRes", "Flight Time": "43 Mins", "Range": "15 km O3+ Transmission", "Weight": "958g" },
    carrier_default: "USPS"
  },
  {
    id: "prod_2",
    name: "Sony Alpha A7 IV Mirrorless Camera",
    brand: "Sony",
    category: "Drones & Cameras",
    sku: "SONY-A7M4-BODY",
    price_cents: 249800,
    rating: 4.9,
    reviews_count: 512,
    stock: 19,
    image_url: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=600&q=80",
    description: "33MP full-frame Exmor R back-illuminated sensor, 4K 60p 10-bit 4:2:2 recording, real-time eye AF, and 759-point phase detection AF.",
    specs: { "Sensor": "33MP Full-Frame Exmor R", "ISO": "100-51200", "Autofocus": "759 Phase Points", "Stabilization": "5-axis In-body 5.5-step", "Weight": "658g" },
    carrier_default: "FEDEX"
  },
  {
    id: "prod_3",
    name: "GoPro HERO12 Black Action Camera",
    brand: "GoPro",
    category: "Drones & Cameras",
    sku: "GOPRO-H12-BLK",
    price_cents: 39900,
    rating: 4.7,
    reviews_count: 894,
    stock: 45,
    image_url: "https://images.unsplash.com/photo-1565849904461-04a58ad377e0?auto=format&fit=crop&w=600&q=80",
    description: "Waterproof action camera with 5.3K60 HDR video, HyperSmooth 6.0 stabilization with 360 Horizon Lock, and Bluetooth audio support.",
    specs: { "Video": "5.3K/60fps, 4K/120fps", "Photo": "27MP Raw", "Waterproof": "33ft (10m) native", "Battery": "Enduro 1720mAh", "Weight": "154g" },
    carrier_default: "USPS"
  },
  {
    id: "prod_4",
    name: "Insta360 X4 8K 360 Waterproof Camera",
    brand: "Insta360",
    category: "Drones & Cameras",
    sku: "INSTA-X4-8K",
    price_cents: 49900,
    rating: 4.8,
    reviews_count: 421,
    stock: 28,
    image_url: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=600&q=80",
    description: "Groundbreaking 8K 360-degree capture with invisible selfie stick effect, AI gesture control, and rugged waterproof construction.",
    specs: { "Resolution": "8K 30fps 360", "Stabilization": "FlowState + Horizon Lock", "Battery": "2290mAh (135 mins)", "Screen": "2.5-inch Gorilla Glass", "Weight": "203g" },
    carrier_default: "USPS"
  },
  {
    id: "prod_5",
    name: "DJI Mini 4 Pro Fly More Combo",
    brand: "DJI",
    category: "Drones & Cameras",
    sku: "DJI-MINI4P-FMC",
    price_cents: 109900,
    rating: 4.9,
    reviews_count: 630,
    stock: 22,
    image_url: "https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=600&q=80",
    description: "Under-249g ultralight drone featuring omnidirectional obstacle sensing, 4K/60fps HDR true vertical shooting, and 20km FHD transmission.",
    specs: { "Weight": "< 249g (No FAA reg needed)", "Video": "4K/60fps HDR", "Flight Time": "34 Mins per battery", "Sensor": "1/1.3-inch CMOS f/1.7", "Transmission": "O4 20km" },
    carrier_default: "USPS"
  },
  {
    id: "prod_6",
    name: "Fujifilm X-T5 Mirrorless Camera (Silver)",
    brand: "Fujifilm",
    category: "Drones & Cameras",
    sku: "FUJI-XT5-SLV",
    price_cents: 169900,
    rating: 4.8,
    reviews_count: 310,
    stock: 12,
    image_url: "https://images.unsplash.com/photo-1512790182412-b19e6d62bc39?auto=format&fit=crop&w=600&q=80",
    description: "40.2MP X-Trans CMOS 5 HR sensor with 7.0 stops of in-body image stabilization, classic analog dial layout, and 1/180,000s max shutter speed.",
    specs: { "Sensor": "40.2MP APS-C X-Trans", "IBIS": "7.0 Stops", "Video": "6.2K/30p 4:2:2 10-Bit", "Display": "3-way tilting LCD", "Weight": "557g" },
    carrier_default: "UPS"
  },
  {
    id: "prod_7",
    name: "Canon EOS R6 Mark II Full-Frame",
    brand: "Canon",
    category: "Drones & Cameras",
    sku: "CANON-R6M2-BODY",
    price_cents: 229900,
    rating: 4.9,
    reviews_count: 440,
    stock: 16,
    image_url: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&q=80",
    description: "24.2MP CMOS sensor with continuous shooting up to 40 fps electronic shutter, 6K oversampled uncropped 4K 60p, and Dual Pixel CMOS AF II.",
    specs: { "Sensor": "24.2MP Full-Frame CMOS", "Speed": "40 fps Electronic", "Autofocus": "Dual Pixel CMOS AF II", "IBIS": "Up to 8.0 Stops", "Card Slots": "Dual UHS-II SD" },
    carrier_default: "FEDEX"
  },
  {
    id: "prod_8",
    name: "DJI Osmo Pocket 3 Creator Combo",
    brand: "DJI",
    category: "Drones & Cameras",
    sku: "DJI-POCKET3-CC",
    price_cents: 66900,
    rating: 4.9,
    reviews_count: 780,
    stock: 31,
    image_url: "https://images.unsplash.com/photo-1495707902641-75cac588d2e9?auto=format&fit=crop&w=600&q=80",
    description: "Pocket-sized gimbal camera with 1-inch CMOS sensor, 2-inch rotatable OLED touchscreen, 4K/120fps recording, and full-pixel fast focusing.",
    specs: { "Sensor": "1-inch CMOS", "Screen": "2.0-inch Rotatable OLED", "Stabilization": "3-Axis Mechanical", "Mic": "DJI Mic 2 Transmitter Included", "Weight": "179g" },
    carrier_default: "USPS"
  },

  // ── 2. Audio & Studio Sound (8 products) ──
  {
    id: "prod_9",
    name: "Sony WH-1000XM5 Wireless Headphones",
    brand: "Sony",
    category: "Audio & Sound",
    sku: "SONY-WH1000XM5-BLK",
    price_cents: 39900,
    rating: 4.8,
    reviews_count: 1420,
    stock: 52,
    image_url: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80",
    description: "Industry-leading noise cancellation with Auto NC Optimizer, 8 microphones, 30-hr battery life with ultra-quick charging, and LDAC audio.",
    specs: { "Battery": "30 Hours (ANC On)", "Driver": "30mm Precision Engineered", "Codecs": "LDAC, AAC, SBC", "Weight": "250g", "Multipoint": "2 Devices Simultaneous" },
    carrier_default: "USPS"
  },
  {
    id: "prod_10",
    name: "Bose QuietComfort Ultra Headphones",
    brand: "Bose",
    category: "Audio & Sound",
    sku: "BOSE-QC-ULTRA-BLK",
    price_cents: 42900,
    rating: 4.8,
    reviews_count: 870,
    stock: 38,
    image_url: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=600&q=80",
    description: "Breakthrough spatialized audio with Bose Immersive Audio, custom acoustic architecture, CustomTune sound calibration, and lush comfort.",
    specs: { "Battery": "24 Hours (18 hrs Immersive)", "Noise Cancelling": "Quiet, Aware, Immersion", "Microphones": "Beamforming Array", "Bluetooth": "5.3 with Snapdragon Sound", "Weight": "252g" },
    carrier_default: "USPS"
  },
  {
    id: "prod_11",
    name: "Apple AirPods Max (Space Gray)",
    brand: "Apple",
    category: "Audio & Sound",
    sku: "APPL-AIRPODS-MAX-SG",
    price_cents: 54900,
    rating: 4.7,
    reviews_count: 1105,
    stock: 24,
    image_url: "https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=600&q=80",
    description: "Apple-designed dynamic driver providing high-fidelity audio, computational audio with H1 chips in each cup, active noise cancellation, and Spatial Audio.",
    specs: { "Chassis": "Anodized Aluminum & Mesh", "Chip": "Dual Apple H1", "Battery": "20 Hours with ANC", "Audio": "Personalized Spatial Audio", "Weight": "384.8g" },
    carrier_default: "UPS"
  },
  {
    id: "prod_12",
    name: "Sennheiser Momentum 4 Wireless",
    brand: "Sennheiser",
    category: "Audio & Sound",
    sku: "SENN-M4-BLK",
    price_cents: 34900,
    rating: 4.7,
    reviews_count: 640,
    stock: 29,
    image_url: "https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=600&q=80",
    description: "Signature Sennheiser sound with an astounding 60-hour battery life, 42mm transducer system, adaptive noise cancellation, and sound personalization.",
    specs: { "Battery": "60 Hours Marathon Life", "Transducer": "42mm Audiophile Grade", "Frequency": "6 Hz - 22 kHz", "Codecs": "aptX Adaptive, AAC, SBC", "Weight": "293g" },
    carrier_default: "USPS"
  },
  {
    id: "prod_13",
    name: "Shure SM7B Vocal Dynamic Microphone",
    brand: "Shure",
    category: "Audio & Sound",
    sku: "SHURE-SM7B-STUDIO",
    price_cents: 39900,
    rating: 5.0,
    reviews_count: 2190,
    stock: 40,
    image_url: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=600&q=80",
    description: "The gold standard for broadcast, podcasting, and vocal recording. Smooth, flat, wide-range frequency response with electromagnetic hum shielding.",
    specs: { "Type": "Dynamic (Moving Coil)", "Polar Pattern": "Cardioid", "Frequency Response": "50 Hz to 20 kHz", "Connector": "Three-pin Professional XLR", "Weight": "765g" },
    carrier_default: "USPS"
  },
  {
    id: "prod_14",
    name: "Sonos Era 300 Spatial Audio Speaker",
    brand: "Sonos",
    category: "Audio & Sound",
    sku: "SONOS-ERA300-WHT",
    price_cents: 44900,
    rating: 4.8,
    reviews_count: 480,
    stock: 18,
    image_url: "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=600&q=80",
    description: "Revolutionary acoustic design featuring six optimally positioned drivers all around the front, sides, and top to support Dolby Atmos Spatial Audio.",
    specs: { "Amplifiers": "6 Class-D Digital Amps", "Spatial Audio": "Dolby Atmos Supported", "Connectivity": "Wi-Fi 6, Bluetooth 5.0, USB-C Line-In", "Microphones": "Far-field with Trueplay", "Weight": "4.47 kg" },
    carrier_default: "UPS"
  },
  {
    id: "prod_15",
    name: "Marshall Stanmore III Bluetooth Speaker",
    brand: "Marshall",
    category: "Audio & Sound",
    sku: "MARSH-STAN3-BLK",
    price_cents: 37900,
    rating: 4.8,
    reviews_count: 590,
    stock: 21,
    image_url: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=600&q=80",
    description: "Legendary Marshall rock 'n' roll design with outward-angled tweeters, updated waveguides, Dynamic Loudness, and room-filling analog punch.",
    specs: { "Power": "80W Class D Amplification", "Frequency": "45–20,000 Hz", "Inputs": "Bluetooth 5.2, 3.5mm Aux, RCA", "Design": "PVC-free, 70% recycled plastic", "Weight": "4.25 kg" },
    carrier_default: "FEDEX"
  },
  {
    id: "prod_16",
    name: "Audio-Technica AT2020USB-X Cardioid Mic",
    brand: "Audio-Technica",
    category: "Audio & Sound",
    sku: "AT-2020USBX-MIC",
    price_cents: 12900,
    rating: 4.7,
    reviews_count: 810,
    stock: 64,
    image_url: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=600&q=80",
    description: "High-resolution A/D converter with up to 24-bit/96 kHz sampling rate for crystal-clear studio reproduction, capacitive mute button, and headphone jack.",
    specs: { "Bit Depth": "24-bit / 96 kHz", "Output": "USB Type-C", "Monitoring": "Zero-latency Headphone Jack", "Pattern": "Cardioid Directional", "Weight": "373g" },
    carrier_default: "USPS"
  },

  // ── 3. Gaming & VR Gear (8 products) ──
  {
    id: "prod_17",
    name: "Sony PlayStation 5 Pro Console (2TB)",
    brand: "Sony",
    category: "Gaming & VR",
    sku: "PS5-PRO-2TB-ED",
    price_cents: 69900,
    rating: 4.9,
    reviews_count: 1890,
    stock: 25,
    image_url: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=600&q=80",
    description: "Upgraded GPU with PlayStation Spectral Super Resolution (PSSR) AI upscaling, advanced ray tracing, 60fps high-fidelity gameplay, and 2TB SSD.",
    specs: { "Storage": "2TB Ultra-High Speed SSD", "GPU": "67% More Compute Units", "Upscaling": "PSSR Machine Learning", "Output": "Supports 8K, 4K 120Hz, VRR", "Weight": "3.1 kg" },
    carrier_default: "FEDEX"
  },
  {
    id: "prod_18",
    name: "Meta Quest 3 Mixed Reality Headset (512GB)",
    brand: "Meta",
    category: "Gaming & VR",
    sku: "META-QUEST3-512GB",
    price_cents: 49900,
    rating: 4.8,
    reviews_count: 940,
    stock: 33,
    image_url: "https://images.unsplash.com/photo-1622979135225-d2ba269bc1df?auto=format&fit=crop&w=600&q=80",
    description: "Breakthrough mixed reality with high-res full-color passthrough, Snapdragon XR2 Gen 2 processor, 4K+ Infinite Display, and Touch Plus controllers.",
    specs: { "Display": "2064x2208 pixels per eye", "Optics": "Pancake Lenses", "Processor": "Snapdragon XR2 Gen 2", "Audio": "3D Spatial Sound", "Weight": "515g" },
    carrier_default: "UPS"
  },
  {
    id: "prod_19",
    name: "Nintendo Switch OLED Model (White)",
    brand: "Nintendo",
    category: "Gaming & VR",
    sku: "NINT-SWITCH-OLED-W",
    price_cents: 34900,
    rating: 4.9,
    reviews_count: 3200,
    stock: 58,
    image_url: "https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?auto=format&fit=crop&w=600&q=80",
    description: "Vibrant 7-inch OLED screen, wide adjustable tabletop stand, dock with wired LAN port, 64GB internal storage, and enhanced onboard audio.",
    specs: { "Screen": "7.0-inch OLED (720p Handheld / 1080p TV)", "Storage": "64GB Internal + MicroSD", "Battery": "4.5 to 9 Hours", "Weight": "420g with Joy-Con" },
    carrier_default: "USPS"
  },
  {
    id: "prod_20",
    name: "Logitech G Pro X Superlight 2 Gaming Mouse",
    brand: "Logitech",
    category: "Gaming & VR",
    sku: "LOGI-GPROX-SL2-W",
    price_cents: 15900,
    rating: 4.9,
    reviews_count: 1450,
    stock: 75,
    image_url: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=600&q=80",
    description: "Ultralight 60g esports icon featuring LIGHTFORCE hybrid optical-mechanical switches, HERO 2 sensor with 32,000 DPI, and 95-hour battery life.",
    specs: { "Weight": "60 Grams", "Sensor": "HERO 2 32,000 DPI", "Polling Rate": "Up to 4,000 Hz", "Battery": "95 Hours Constant Motion", "Switches": "LIGHTFORCE Hybrid" },
    carrier_default: "USPS"
  },
  {
    id: "prod_21",
    name: "Razer BlackWidow V4 Pro Mechanical Keyboard",
    brand: "Razer",
    category: "Gaming & VR",
    sku: "RAZER-BW4-PRO-GRN",
    price_cents: 22900,
    rating: 4.7,
    reviews_count: 670,
    stock: 36,
    image_url: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80",
    description: "Full battlestation immersion with Razer Command Dial, 8 dedicated macro keys, 8,000Hz hyperpolling, magnetic plush leatherette wrist rest, and Chroma RGB.",
    specs: { "Switches": "Razer Green Clicky Mechanical", "Polling": "8000 Hz HyperPolling", "Keycaps": "Doubleshot ABS", "Connectivity": "Detachable Dual USB-C", "Macros": "8 Dedicated Keys" },
    carrier_default: "USPS"
  },
  {
    id: "prod_22",
    name: "Steam Deck OLED (1TB Edition)",
    brand: "Valve",
    category: "Gaming & VR",
    sku: "VALVE-SDECK-1TB",
    price_cents: 64900,
    rating: 5.0,
    reviews_count: 1650,
    stock: 20,
    image_url: "https://images.unsplash.com/photo-1612287233207-6c2e2c84e1b8?auto=format&fit=crop&w=600&q=80",
    description: "7.4-inch 90Hz HDR OLED display with custom 6nm AMD APU, Wi-Fi 6E, 50Wh battery offering 3–12 hours of gameplay, and premium anti-glare etched glass.",
    specs: { "Screen": "7.4-inch HDR OLED 90Hz", "APU": "6nm AMD Sephiroth", "RAM": "16 GB LPDDR5", "Storage": "1TB NVMe SSD", "Weight": "640g" },
    carrier_default: "FEDEX"
  },
  {
    id: "prod_23",
    name: "Xbox Wireless Controller (Carbon Black)",
    brand: "Microsoft",
    category: "Gaming & VR",
    sku: "MS-XBOX-CTRL-BLK",
    price_cents: 5900,
    rating: 4.8,
    reviews_count: 4100,
    stock: 120,
    image_url: "https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?auto=format&fit=crop&w=600&q=80",
    description: "Modernized ergonomic design with sculpted surfaces, hybrid D-pad, textured grip on triggers and bumpers, and 3.5mm audio jack.",
    specs: { "Compatibility": "Xbox Series X|S, Xbox One, PC, Android, iOS", "Battery": "Up to 40 Hours (AA)", "Connectivity": "Xbox Wireless & Bluetooth", "Weight": "287g" },
    carrier_default: "USPS"
  },
  {
    id: "prod_24",
    name: "SteelSeries Arctis Nova Pro Wireless",
    brand: "SteelSeries",
    category: "Gaming & VR",
    sku: "STEEL-NOVA-PRO-WL",
    price_cents: 34900,
    rating: 4.8,
    reviews_count: 730,
    stock: 27,
    image_url: "https://images.unsplash.com/photo-1599669454699-248893623440?auto=format&fit=crop&w=600&q=80",
    description: "Audiophile-grade Nova Pro Acoustic System with Active Noise Cancellation, Infinity Power System dual-battery hot swapping, and multi-system dual USB DAC.",
    specs: { "DAC": "Base Station with OLED Screen", "Battery": "Infinity Hot-Swap (Unlimited)", "ANC": "4-mic Hybrid Active NC", "Compatibility": "PC, Mac, PlayStation, Switch", "Weight": "338g" },
    carrier_default: "USPS"
  },

  // ── 4. Computing & Laptops (6 products) ──
  {
    id: "prod_25",
    name: "Apple MacBook Pro 16 M3 Max (36GB/1TB)",
    brand: "Apple",
    category: "Computing & Laptops",
    sku: "APPL-MBP16-M3MAX",
    price_cents: 349900,
    rating: 5.0,
    reviews_count: 512,
    stock: 11,
    image_url: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=600&q=80",
    description: "16-core CPU, 40-core GPU M3 Max chip with 16.2-inch Liquid Retina XDR display (1600 nits peak), 22 hours of battery life, and Space Black aluminum finish.",
    specs: { "Chip": "Apple M3 Max 16-Core", "Unified Memory": "36 GB", "Display": "16.2-inch Liquid Retina XDR 120Hz", "Storage": "1TB SSD", "Weight": "2.16 kg" },
    carrier_default: "FEDEX"
  },
  {
    id: "prod_26",
    name: "Dell XPS 15 OLED Laptop (i9/32GB/1TB)",
    brand: "Dell",
    category: "Computing & Laptops",
    sku: "DELL-XPS15-9530",
    price_cents: 229900,
    rating: 4.7,
    reviews_count: 380,
    stock: 15,
    image_url: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=600&q=80",
    description: "13th Gen Intel Core i9-13900H with NVIDIA GeForce RTX 4070, 3.5K OLED InfinityEdge touch display, and CNC machined aluminum chassis.",
    specs: { "CPU": "Intel Core i9-13900H", "GPU": "NVIDIA RTX 4070 8GB", "RAM": "32GB DDR5 4800MHz", "Display": "15.6-inch 3.5K OLED Touch", "Weight": "1.92 kg" },
    carrier_default: "UPS"
  },
  {
    id: "prod_27",
    name: "Keychron Q1 Pro Wireless Custom Keyboard",
    brand: "Keychron",
    category: "Computing & Laptops",
    sku: "KEYCHRON-Q1PRO-KPB",
    price_cents: 19900,
    rating: 4.9,
    reviews_count: 890,
    stock: 42,
    image_url: "https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=600&q=80",
    description: "75% layout QMK/VIA wireless mechanical keyboard with CNC machined aluminum body, double-gasket acoustic mount, hot-swappable sockets, and PBT keycaps.",
    specs: { "Body": "Full CNC 6063 Aluminum", "Connectivity": "Bluetooth 5.1 & Type-C", "Mount": "Double-Gasket Design", "Switches": "Keychron K Pro Red (Pre-Lubed)", "Weight": "1.74 kg" },
    carrier_default: "USPS"
  },
  {
    id: "prod_28",
    name: "LG 27MD5KL-B UltraFine 5K Display",
    brand: "LG",
    category: "Computing & Laptops",
    sku: "LG-27UF-5K-DISP",
    price_cents: 129900,
    rating: 4.6,
    reviews_count: 240,
    stock: 10,
    image_url: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=600&q=80",
    description: "27-inch 5K (5120 x 2880) IPS display with 99% DCI-P3 wide color gamut, Thunderbolt 3 94W pass-through charging, and built-in camera/speakers.",
    specs: { "Resolution": "5120 x 2880 at 60Hz", "Panel": "IPS 500 nits Brightness", "Color": "99% DCI-P3", "Ports": "1x Thunderbolt 3, 3x USB-C", "Weight": "8.5 kg" },
    carrier_default: "FEDEX"
  },
  {
    id: "prod_29",
    name: "CalDigit TS4 Thunderbolt 4 Station (18 Ports)",
    brand: "CalDigit",
    category: "Computing & Laptops",
    sku: "CALDIGIT-TS4-DOCK",
    price_cents: 39900,
    rating: 4.9,
    reviews_count: 730,
    stock: 35,
    image_url: "https://images.unsplash.com/photo-1544652478-6653e09f18a2?auto=format&fit=crop&w=600&q=80",
    description: "The ultimate 18-port docking hub with 98W Power Delivery, 2.5GbE ethernet, dual 6K 60Hz display support, and UHS-II SD/microSD slots.",
    specs: { "Ports": "18 Extreme Expansion Ports", "Charging": "98W Host Power Delivery", "Ethernet": "2.5 Gigabit LAN", "Display": "Up to Single 8K or Dual 6K", "Chassis": "Solid Aluminum" },
    carrier_default: "USPS"
  },
  {
    id: "prod_30",
    name: "Samsung 4TB 990 PRO NVMe SSD Heatsink",
    brand: "Samsung",
    category: "Computing & Laptops",
    sku: "SAMS-990PRO-4TB",
    price_cents: 34900,
    rating: 4.9,
    reviews_count: 1420,
    stock: 50,
    image_url: "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=600&q=80",
    description: "Top-tier PCIe Gen 4.0 x4 internal solid state drive with up to 7,450 MB/s read, custom thermal heatsink, and smart power efficiency.",
    specs: { "Capacity": "4 Terabytes", "Seq Read": "7,450 MB/s", "Seq Write": "6,900 MB/s", "Interface": "PCIe 4.0 NVMe 2.0", "Compatibility": "PC & PS5 Direct" },
    carrier_default: "USPS"
  },

  // ── 5. Smart Home & IoT (8 products) ──
  {
    id: "prod_31",
    name: "Smart IoT Matter Multi-Protocol Home Hub",
    brand: "HomePilot",
    category: "Smart Home & IoT",
    sku: "IOT-HUB-MATTER-01",
    price_cents: 14900,
    rating: 4.8,
    reviews_count: 530,
    stock: 48,
    image_url: "https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=600&q=80",
    description: "Universal smart controller running Matter, Thread, Zigbee 3.0, and Z-Wave protocols with local automation execution and zero cloud lag.",
    specs: { "Protocols": "Matter, Thread, Zigbee, Z-Wave, Wi-Fi", "Storage": "32GB Local Flash", "Security": "Hardware Secure Enclave", "Power": "PoE or USB-C 5V" },
    carrier_default: "USPS"
  },
  {
    id: "prod_32",
    name: "Google Nest Learning Thermostat (4th Gen)",
    brand: "Google",
    category: "Smart Home & IoT",
    sku: "GOOG-NEST-T4-POL",
    price_cents: 27900,
    rating: 4.7,
    reviews_count: 1240,
    stock: 35,
    image_url: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=600&q=80",
    description: "Domed liquid glass display, dynamic borderless UI, Smart Schedule learning, and Matter compatibility to save an average of 15% on energy bills.",
    specs: { "Display": "High-Res Borderless Domed Glass", "Sensors": "Temperature, Humidity, Proximity", "Compatibility": "98% of HVAC Systems", "Support": "Matter & Google Home" },
    carrier_default: "USPS"
  },
  {
    id: "prod_33",
    name: "Philips Hue Smart Lighting Starter Kit (4-Pack)",
    brand: "Philips Hue",
    category: "Smart Home & IoT",
    sku: "PHIL-HUE-STARTER4",
    price_cents: 19900,
    rating: 4.9,
    reviews_count: 2400,
    stock: 60,
    image_url: "https://images.unsplash.com/photo-1550524514-9b6d859b4c02?auto=format&fit=crop&w=600&q=80",
    description: "Four White and Color Ambiance A19 bulbs, Hue Bridge, and smart button. 16 million colors, automated sunrise routines, and dynamic music sync.",
    specs: { "Bulbs": "4x E26 1100 Lumen (75W Equivalent)", "Colors": "16 Million Colors + Tunable White", "Bridge": "Hue Bridge Hub Included", "Protocol": "Zigbee & Bluetooth" },
    carrier_default: "USPS"
  },
  {
    id: "prod_34",
    name: "Ring Video Doorbell Pro 2 (Hardwired)",
    brand: "Ring",
    category: "Smart Home & IoT",
    sku: "RING-VDB-PRO2",
    price_cents: 24900,
    rating: 4.6,
    reviews_count: 1670,
    stock: 44,
    image_url: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=600&q=80",
    description: "1536p HD Head-to-Toe Video, 3D Motion Detection with radar-powered Bird's Eye View, Two-Way Talk with Audio+, and Alexa Greetings.",
    specs: { "Resolution": "1536p HD Head-to-Toe", "Radar": "3D Motion Detection", "Night Vision": "Color Night Vision", "Power": "Hardwired 16-24 VAC", "Connectivity": "Dual-Band 2.4/5GHz" },
    carrier_default: "USPS"
  },
  {
    id: "prod_35",
    name: "Roborock S8 MaxV Ultra Robot Vacuum",
    brand: "Roborock",
    category: "Smart Home & IoT",
    sku: "ROBO-S8MAXV-ULTRA",
    price_cents: 179900,
    rating: 4.9,
    reviews_count: 410,
    stock: 9,
    image_url: "https://images.unsplash.com/photo-1518640467707-6811f4a6ab73?auto=format&fit=crop&w=600&q=80",
    description: "10,000 Pa extreme suction, FlexiArm side brush for zero dead corners, 60°C hot water mop washing, auto dirt detection, and built-in voice assistant.",
    specs: { "Suction": "10,000 Pa HyperForce", "Dock": "8-in-1 RockDock Ultra (Hot Water Wash)", "Mopping": "VibraRise 3.0 (4000x/min)", "Obstacle": "Reactive AI 2.0 Recognition" },
    carrier_default: "FEDEX"
  },
  {
    id: "prod_36",
    name: "Schlage Encode Plus Smart WiFi Deadbolt",
    brand: "Schlage",
    category: "Smart Home & IoT",
    sku: "SCHLAGE-ENC-PLUS-NK",
    price_cents: 31900,
    rating: 4.8,
    reviews_count: 820,
    stock: 26,
    image_url: "https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=600&q=80",
    description: "Apple Home Key compatible smart lock. Tap your iPhone or Apple Watch to unlock with built-in Wi-Fi and Grade 1 commercial security certification.",
    specs: { "Security": "BHMA Grade 1 (Highest Rating)", "Home Key": "NFC Tap to Unlock with iPhone", "Connectivity": "Direct Wi-Fi & Thread", "Codes": "Up to 100 Access Codes" },
    carrier_default: "USPS"
  },
  {
    id: "prod_37",
    name: "Sonos Sub Mini Wireless Subwoofer",
    brand: "Sonos",
    category: "Smart Home & IoT",
    sku: "SONOS-SUB-MINI-BLK",
    price_cents: 42900,
    rating: 4.9,
    reviews_count: 530,
    stock: 22,
    image_url: "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=600&q=80",
    description: "Dual custom force-cancelling woofers inside a sealed architectural cabinet neutralize distortion and generate deep, dynamic low-end bass.",
    specs: { "Woofers": "Dual 6-inch Inward Facing", "Amplifier": "Dual Class-D Digital", "Frequency": "Down to 25 Hz", "Wireless": "5 GHz Dedicated Ultra-Low Latency" },
    carrier_default: "UPS"
  },
  {
    id: "prod_38",
    name: "Nanoleaf Shapes Hexagons Smarter Kit (9 Panels)",
    brand: "Nanoleaf",
    category: "Smart Home & IoT",
    sku: "NANO-HEX-9PK",
    price_cents: 19900,
    rating: 4.7,
    reviews_count: 980,
    stock: 37,
    image_url: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=600&q=80",
    description: "Modular ultra-thin smart LED light panels with Connect+ technology, music visualizer sync, screen mirror immersion, and touch control.",
    specs: { "Panels": "9 Hexagon Light Panels", "Luminance": "100 Lumens per Panel", "Color Range": "16M Colors & 1200K-6500K White", "Features": "Touch Reactive, Rhythm Sync" },
    carrier_default: "USPS"
  },

  // ── 6. Wearables & Fitness (6 products) ──
  {
    id: "prod_39",
    name: "Apple Watch Ultra 2 (Titanium/Ocean Band)",
    brand: "Apple",
    category: "Wearables & Fitness",
    sku: "APPL-WAT-ULTRA2-OCN",
    price_cents: 79900,
    rating: 4.9,
    reviews_count: 1420,
    stock: 28,
    image_url: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80",
    description: "49mm aerospace-grade titanium case with S9 SiP, 3000-nit Always-On display, precision dual-frequency GPS, 36-hr battery life, and 100m water resistance.",
    specs: { "Case": "49mm Titanium", "Display": "3000 nits Sapphire Crystal", "Battery": "Up to 72 Hours in Low Power", "Depth": "100m Water / EN13319 Dive Certified" },
    carrier_default: "USPS"
  },
  {
    id: "prod_40",
    name: "Garmin Fenix 7 Pro Sapphire Solar (47mm)",
    brand: "Garmin",
    category: "Wearables & Fitness",
    sku: "GARM-FENIX7P-SOL",
    price_cents: 79900,
    rating: 4.9,
    reviews_count: 610,
    stock: 19,
    image_url: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=600&q=80",
    description: "Multisport GPS watch with solar charging lens, built-in LED flashlight, endurance score, Hill score, and up to 22 days of battery life in smartwatch mode.",
    specs: { "Battery": "Up to 22 Days with Solar", "Glass": "Power Sapphire Solar", "Flashlight": "Variable White & Red LED", "Maps": "TopoActive Multi-Continent Preloaded" },
    carrier_default: "UPS"
  },
  {
    id: "prod_41",
    name: "Oura Ring Gen 3 Horizon (Stealth Black)",
    brand: "Oura",
    category: "Wearables & Fitness",
    sku: "OURA-R3-HOR-STL",
    price_cents: 39900,
    rating: 4.6,
    reviews_count: 890,
    stock: 45,
    image_url: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=600&q=80",
    description: "Titanium smart ring monitoring sleep stages, Readiness score, HRV, heart rate trends, and body temperature variations with zero screen distractions.",
    specs: { "Material": "Durable Lightweight Titanium", "Sensors": "Red & Green LEDs, Infrared PPG, Skin Temp", "Battery": "4 to 7 Days", "Waterproof": "Up to 100m (330 ft)" },
    carrier_default: "USPS"
  },
  {
    id: "prod_42",
    name: "Whoop 4.0 Fitness & Recovery Tracker",
    brand: "Whoop",
    category: "Wearables & Fitness",
    sku: "WHOOP-4-ONYX-KIT",
    price_cents: 23900,
    rating: 4.7,
    reviews_count: 1120,
    stock: 50,
    image_url: "https://images.unsplash.com/photo-1576243345690-4e4b79b63288?auto=format&fit=crop&w=600&q=80",
    description: "Screenless 24/7 biometric sensor providing physiological Strain, Sleep Coach, and Recovery metrics with waterproof on-the-go wireless battery pack.",
    specs: { "Sensors": "5 LEDs (Green, Red, IR), 4 Photodiodes", "Battery": "Wireless Slide-on PowerPack", "Waterproof": "IP68 Submersible to 10m", "Subscription": "Includes 12-Month Access" },
    carrier_default: "USPS"
  },
  {
    id: "prod_43",
    name: "Samsung Galaxy Watch Ultra (47mm LTE)",
    brand: "Samsung",
    category: "Wearables & Fitness",
    sku: "SAMS-GW-ULTRA-LTE",
    price_cents: 64900,
    rating: 4.8,
    reviews_count: 480,
    stock: 22,
    image_url: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=600&q=80",
    description: "Grade 4 Titanium cushion frame, 3nm processor with Galaxy AI health insights, dual-frequency GPS, Emergency Siren, and 10 ATM ocean durability.",
    specs: { "Case": "Grade 4 Titanium (47mm)", "Processor": "3nm Exynos W1000", "Sensors": "BioActive 13-LED Multi-Sensor", "Battery": "Up to 100 Hours (Power Saving)" },
    carrier_default: "USPS"
  },
  {
    id: "prod_44",
    name: "Polar H10 Heart Rate Sensor Chest Strap",
    brand: "Polar",
    category: "Wearables & Fitness",
    sku: "POLAR-H10-STRAP-M",
    price_cents: 8900,
    rating: 4.9,
    reviews_count: 2300,
    stock: 90,
    image_url: "https://images.unsplash.com/photo-1510519138161-58474dfab9c8?auto=format&fit=crop&w=600&q=80",
    description: "The gold standard for ECG heart rate accuracy. Dual simultaneous Bluetooth connections, ANT+, onboard training session memory, and 400-hr battery.",
    specs: { "Measurement": "Medical Grade ECG Electrodes", "Battery": "400 Hours (Coin Cell CR2025)", "Connectivity": "Dual Bluetooth Low Energy & ANT+", "Waterproof": "30m" },
    carrier_default: "USPS"
  },

  // ── 7. Mobile & Tablets (4 products) ──
  {
    id: "prod_45",
    name: "Apple iPad Pro 13 M4 (256GB Wi-Fi Space Black)",
    brand: "Apple",
    category: "Mobile & Tablets",
    sku: "APPL-IPADPRO13-M4",
    price_cents: 129900,
    rating: 4.9,
    reviews_count: 620,
    stock: 18,
    image_url: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=600&q=80",
    description: "Ultra Retina XDR Tandem OLED display (1600 nits HDR), groundbreaking M4 chip with Next-Gen Neural Engine, and impossibly thin 5.1mm chassis.",
    specs: { "Screen": "13-inch Tandem OLED 120Hz", "Chip": "Apple M4 9-Core", "Thickness": "5.1mm (Thinnest Apple Product)", "Cameras": "12MP Wide + LiDAR Scanner", "Weight": "579g" },
    carrier_default: "FEDEX"
  },
  {
    id: "prod_46",
    name: "Samsung Galaxy S24 Ultra (512GB Titanium Black)",
    brand: "Samsung",
    category: "Mobile & Tablets",
    sku: "SAMS-S24U-512GB",
    price_cents: 141900,
    rating: 4.8,
    reviews_count: 1430,
    stock: 25,
    image_url: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=600&q=80",
    description: "Titanium exterior with 200MP Quad Tele camera system, flat 6.8-inch Dynamic AMOLED 2X with Corning Gorilla Armor anti-reflective glass, and S Pen.",
    specs: { "Main Camera": "200MP f/1.7 OIS", "Processor": "Snapdragon 8 Gen 3 for Galaxy", "Display": "6.8-inch QHD+ 2600 nits", "Pen": "Embedded S Pen Included" },
    carrier_default: "UPS"
  },
  {
    id: "prod_47",
    name: "reMarkable 2 Paper Tablet with Marker Plus",
    brand: "reMarkable",
    category: "Mobile & Tablets",
    sku: "REMARK-2-BUNDLE",
    price_cents: 44900,
    rating: 4.7,
    reviews_count: 850,
    stock: 30,
    image_url: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
    description: "The world's thinnest digital notebook at 4.7mm. CANVAS monochrome display feels like real paper for distraction-free note-taking and PDF reading.",
    specs: { "Thickness": "4.7mm", "Display": "10.3-inch CANVAS E-Ink Paper", "Battery": "Up to 2 Weeks Active Use", "Marker": "Marker Plus with Built-In Eraser" },
    carrier_default: "USPS"
  },
  {
    id: "prod_48",
    name: "Anker Prime 27,650mAh Power Bank (250W)",
    brand: "Anker",
    category: "Mobile & Tablets",
    sku: "ANKER-PRIME-250W-PB",
    price_cents: 17900,
    rating: 4.9,
    reviews_count: 1290,
    stock: 55,
    image_url: "https://images.unsplash.com/photo-1609592424364-f6b0f4886650?auto=format&fit=crop&w=600&q=80",
    description: "Massive 27,650mAh capacity with 250W multi-port fast charging, smart digital display showing live wattages, and airline-approved TSA sizing.",
    specs: { "Capacity": "27,650mAh (99.54Wh TSA Compliant)", "Max Output": "250W (140W Single Port PD 3.1)", "Ports": "2x USB-C, 1x USB-A", "Screen": "Full Color Smart Display" },
    carrier_default: "USPS"
  },

  // ── 8. Creator & Studio Gear (4 products) ──
  {
    id: "prod_49",
    name: "Elgato Stream Deck XL (32 Macro Keys)",
    brand: "Elgato",
    category: "Creator & Studio",
    sku: "ELGATO-SDECK-XL",
    price_cents: 24900,
    rating: 4.9,
    reviews_count: 2210,
    stock: 45,
    image_url: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80",
    description: "32 customizable LCD keys with instant tactile feedback. Trigger studio actions, control OBS, launch media, adjust audio, and integrate Smart Home.",
    specs: { "Keys": "32 Customizable LCD Keys", "Interface": "USB 3.0 Type-C", "Stand": "Magnetic Anti-Slip Desktop Stand", "Software": "Stream Deck Plugin Store Compatible" },
    carrier_default: "USPS"
  },
  {
    id: "prod_50",
    name: "RØDECaster Pro II Audio Production Studio",
    brand: "RØDE",
    category: "Creator & Studio",
    sku: "RODE-CASTER-PRO2",
    price_cents: 69900,
    rating: 4.9,
    reviews_count: 490,
    stock: 14,
    image_url: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=600&q=80",
    description: "Ultra-low-noise Revolution PreAmps, quad combo XLR inputs, onboard APHEX audio processing, dual USB-C interfaces, and SMART pads.",
    specs: { "PreAmps": "Ultra-Low-Noise Revolution (-131.5dBV EIN)", "Inputs": "4x Neutrik Combo XLR/Line", "Pads": "8 SMART Customizable Sound Pads", "Touchscreen": "5.5-inch High-Definition Haptic" },
    carrier_default: "FEDEX"
  },
  {
    id: "prod_51",
    name: "Nanlite Forza 60B II Bi-Color LED Monolight",
    brand: "Nanlite",
    category: "Creator & Studio",
    sku: "NANLITE-FORZA-60B2",
    price_cents: 31900,
    rating: 4.8,
    reviews_count: 280,
    stock: 22,
    image_url: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=600&q=80",
    description: "Ultra-compact bi-color studio spotlight with 2700K–6500K CCT range, ultra-quiet fan, Bowens adapter included, and 14,350 lux at 1 meter.",
    specs: { "Output": "14,350 Lux at 1m with Reflector", "CCT Range": "2700K - 6500K Bi-Color", "Color Accuracy": "CRI 96, TLCI 98", "Power": "AC Adapter or Dual NP-F/V-Mount Batteries" },
    carrier_default: "UPS"
  },
  {
    id: "prod_52",
    name: "Sony ZV-E1 Full-Frame Vlogging Camera",
    brand: "Sony",
    category: "Creator & Studio",
    sku: "SONY-ZVE1-BLK",
    price_cents: 219800,
    rating: 4.8,
    reviews_count: 360,
    stock: 15,
    image_url: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=600&q=80",
    description: "12.1MP full-frame sensor designed specifically for content creators. AI auto-framing, dynamic active mode stabilization, and 4K 120p recording.",
    specs: { "Sensor": "12.1MP Full-Frame Exmor R", "AI Features": "Auto-Framing, Framing Stabilizer, Multiple Face Recognition", "Audio": "Intelligent 3-Capsule Directional Mic", "Weight": "483g" },
    carrier_default: "FEDEX"
  }
];
