import { Claim, Dispute, EvidenceItem } from '../types';

export interface VerificationResult {
  verified: boolean;
  errors: string[];
  verifiedClaims: Claim[];
}

/**
 * Deterministic code-based claim verifier
 * Evaluates every factual claim generated by the AI against the Evidence Vault.
 * Plain code, NOT the LLM, checks every fact.
 */
export function verifyDraftClaims(
  claims: Claim[],
  evidenceItems: EvidenceItem[],
  dispute: Dispute
): VerificationResult {
  const errors: string[] = [];
  const verifiedClaims: Claim[] = [];
  const evidenceMap = new Map<string, EvidenceItem>();

  for (const item of evidenceItems) {
    evidenceMap.set(item.id, item);
  }

  if (claims.length === 0) {
    errors.push('Draft contains no factual claims with citations');
    return {
      verified: false,
      errors,
      verifiedClaims: [],
    };
  }

  for (const claim of claims) {
    const verifiedClaim: Claim = { ...claim };

    // 1. Evidence item existence check
    const evidence = evidenceMap.get(claim.evidence_id);
    if (!evidence) {
      const err = `Claim cites non-existent evidence ID: "${claim.evidence_id}"`;
      errors.push(err);
      verifiedClaim.verified = false;
      verifiedClaim.mismatch_reason = err;
      verifiedClaims.push(verifiedClaim);
      continue;
    }

    const contentLower = evidence.content.toLowerCase();
    const expectedLower = claim.expected_value.trim().toLowerCase();

    // 2. Fact-specific matching
    let isMatch = false;
    let mismatchDetail = '';

    switch (claim.claim_type) {
      case 'TRACKING_NUMBER':
        // Check if the expected tracking number appears exactly in the evidence content
        if (contentLower.includes(expectedLower)) {
          isMatch = true;
        } else {
          mismatchDetail = `Claimed tracking number "${claim.expected_value}" was not found in vault evidence "${evidence.title}"`;
        }
        break;

      case 'TRANSACTION_AMOUNT':
        // Extract numbers and check for match against dispute or order cents
        const claimedCents = Math.round(parseFloat(claim.expected_value.replace(/[^0-9.]/g, '')) * 100);
        if (claimedCents === dispute.amount_cents || contentLower.includes(claimedCents.toString()) || contentLower.includes(claim.expected_value)) {
          isMatch = true;
        } else {
          mismatchDetail = `Claimed amount "${claim.expected_value}" ($${(claimedCents / 100).toFixed(2)}) does not match dispute amount ($${(dispute.amount_cents / 100).toFixed(2)})`;
        }
        break;

      case 'SHIPPING_DATE':
      case 'DELIVERY_DATE':
        // Match ISO date substring (e.g. YYYY-MM-DD)
        const dateMatch = claim.expected_value.match(/\d{4}-\d{2}-\d{2}/);
        const dateStr = dateMatch ? dateMatch[0] : expectedLower;
        if (contentLower.includes(dateStr) || evidence.captured_at.includes(dateStr)) {
          isMatch = true;
        } else {
          mismatchDetail = `Claimed date "${claim.expected_value}" does not match recorded vault timestamp`;
        }
        break;

      case 'DELIVERY_ADDRESS':
        // Check if city, postal code or street substring matches
        const addressParts = claim.expected_value.split(',').map((p) => p.trim().toLowerCase()).filter(Boolean);
        const matchedParts = addressParts.filter((part) => contentLower.includes(part));
        if (matchedParts.length > 0 || contentLower.includes(expectedLower)) {
          isMatch = true;
        } else {
          mismatchDetail = `Claimed address "${claim.expected_value}" does not match shipping address in vault`;
        }
        break;

      case 'BUYER_NAME':
        if (contentLower.includes(expectedLower)) {
          isMatch = true;
        } else {
          mismatchDetail = `Claimed buyer name "${claim.expected_value}" does not match order record`;
        }
        break;

      default:
        // Generic content verification
        if (contentLower.includes(expectedLower)) {
          isMatch = true;
        } else {
          mismatchDetail = `Expected claim value "${claim.expected_value}" not found in cited evidence`;
        }
        break;
    }

    if (isMatch) {
      verifiedClaim.verified = true;
      delete verifiedClaim.mismatch_reason;
    } else {
      errors.push(mismatchDetail);
      verifiedClaim.verified = false;
      verifiedClaim.mismatch_reason = mismatchDetail;
    }

    verifiedClaims.push(verifiedClaim);
  }

  return {
    verified: errors.length === 0,
    errors,
    verifiedClaims,
  };
}
